### ISSUE TITLE
f string not rendered

### ISSUE THREAD

**Issue by alecandido** [AleCandido/human_dates#6]
The following has been printed explicitly by the `time_ago_in_words` function:
```python
"a week {suffix[to]}"
```

**Comment by felixhekhorn** [comment]
this is closed by https://github.com/AleCandido/human_dates/commit/9780fb24742e9b6fd361fc91b8441f8283d7cd2a isn't it?

**Comment by alecandido** [comment]
Yes you are right, I forgot to close
