### ISSUE TITLE
Bug: date-based repr can be misleading

### ISSUE THREAD

**Issue by felixhekhorn** [AleCandido/human_dates#7]
## Description
when showing a date-based string (i.e. yesterday and older) all time related difference (hh:mm:ss) should be discarded, since otherwise this can lead to misleading output

## Example
- take as a reference value 01.01.2020 23:45
- on 02.01.2020 23:30 this will lead to "23 hours ago" - fine
- on 02.01.2020 23:50 this will lead to "yesterday" - fine
- on 03.01.2020 00:10 this will still lead to "yesterday", but really meaning 24h ago - this is a bug

## Proposed Solution
if the difference is more then 24 hours, recompute the difference only using dates (but not times)

**Comment by alecandido** [comment]
As already said: I agree 100%, I will try to fix during the next meeting (should take ~1 hour just to adjust all the tests).
